### ISSUE TITLE
nemo: SVG and PNG files "disappears" after editing a copy of it

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/-mint20.2-beta#20] opened 2021-06-19 13:40 UTC
(Issue #2623 was on high verbose, so i made a total re-edit here: more precise, concise, short, and more general...)

Restarted from a USB STICK for some quick Mint 20.2 Cinnamon BETA tests...
GOOD NEWS: https://github.com/linuxmint/nemo/issues/2736 is now FIXED
BAD NEWS: https://github.com/linuxmint/nemo/issues/2623 was fixed but now is still BUGGED

![Loading-image](https://user-images.githubusercontent.com/31940713/122644174-ea2d7a00-d0e1-11eb-9145-f069b46bc6a4.png)

**Issue**
I create some PNG or SVG with any software. I make a duplicate. Then i edit this copy and save it while Nemo is displaying some other directory. Then i open the directory to see it, but my edited copy is apparently lost, and there is an endless "Loading" being displayed.

**Steps to reproduce**
NOTE: MAKE SURE YOU NEVER CLOSE OR QUIT NEMO during all of the following steps.
1. Nemo > View > Show Thumbnails
1. Create some PNG or SVG, using some image editing software such as Drawing, or Inkscape, or GIMP, etc. Save it into ~/Pictures or any other directory.
1. Using Nemo, duplicate this PNG or SVG file: select it, then click Edit > Duplicate.
1. Right-click to open this copy into your image editing software.
1. Now, change directory. (Go to parent directory, for example.) So now you don’t see your duplicated image in Nemo, but without closing Nemo.
1. Edit your Test-Image (copy).png and save it.
1. Open this ~/Pictures directory. See? Your edited copy disappeared and Nemo looks like being stuck in an endless loading cycle...

Getting out of this directory and then back again solves this. It is solved easily, but this can happen frequently and so it is really bothering...

**Expected behaviour**
When editing some image (copy).png or some image (copy).svg, while Nemo is into some other directory, i would expect to see my updated image when i go back into this ~/Pictures directory. But the image is gone! Lost!

**Comment by SebastJava** [comment] 2021-06-19 17:02
Oops!
I re-tested... It goes okay, no bug, when i follow these simplified steps up here ▲

But... i followed the more complex, detailed steps in the https://github.com/linuxmint/nemo/issues/2623 OP, and then **i still get this bug.** I did those exact same steps, except i was replacing Inkscape with Drawing, because i was just doing this on a USB boot key.

I am puzzled and tired. I need to take a break. I'll think about this later. I'll try not to make it as high verbose as #2623 was... Sorry about this confusion.

**Comment by SebastJava** [comment] 2021-06-19 19:08
EDITED OP Steps to reproduce:
* Inserted line 4: Right-click to open this copy into your image editing software.

Apparently, the way this copy is opened makes a difference !!? Re-re-re tested and i will probably re-test this again.

**Comment by SebastJava** [comment] 2021-06-20 01:02
UPDATE: I still get this bug WITHOUT DOING ANY DUPLICATE. I skipped step 3. So, this is more universal than i thought.

So, it looks like the key factors are simply:
1. right-click to re-open in your preferred image editing software
2. change directory
3. edit and save
And... boom! When i go back to my ~/Pictures directory, the image is gone!

**Comment by xenopeek** [comment] 2021-06-20 09:08
I can reproduce this issue booted from the Linux Mint 20.2 Cinnamon beta ISO with the following steps.

All I did after booting to the desktop was lower the desktop resolution for video capture, hide desktop icons to not distract and pin Drawing to the panel for easy access. Nothing else changed. The ISO was run in VirtualBox with 3 GB RAM assigned. Video capture was done with Peek from the host system.

Steps to reproduce the issue:

1. Open Nemo and go to the Pictures directory
2. Open Drawing and draw some squiggly colored lines
3. Save the image to the Pictures directory and **exit** Drawing
4. Wait in Nemo until the saved image is shown with its thumbnail
5. Right-click the saved image in Nemo and select Open With > Drawing
6. Switch back to Nemo and go up one directory
7. Switch back to Drawing and add some differently colored lines to the image
8. Save the image and **exit** Drawing
9. In Nemo go into the Pictures directory and the image isn't shown and there is an infinite "loading" shown in bottom right

After closing Nemo and going back to the Pictures directory the modified image is shown correctly.

https://user-images.githubusercontent.com/21159972/122668281-8d03f800-d1b7-11eb-956e-742314407ac6.mp4

**Comment by xenopeek** [comment] 2021-06-20 09:17
The same is reproducible with Caja from the 20.2 MATE beta ISO. Not with Thunar from the 20.2 Xfce beta ISO. It is also reproducible with Nautilus after installing that file manager.

So this looks like a very old bug in Nautilus also present in the code of its forks Nemo (forked from Nautilus 3) and Caja (forked from Nautilus 2).

**Comment by SebastJava** [comment] 2021-06-20 13:59
>     3. Save the image to the Pictures directory and **exit** Drawing
>     [...]
>     8. Save the image and **exit** Drawing

I am not sure you have to **exit** Drawing. **With or without exit,** it is bugged. But then it may sounds ridiculous to right-click to open in Drawing when it is already opened. So, i did this alternate test using Drawing and then Pix, **without any exit:**

1. Open Nemo and go to the Pictures directory
1. Open Drawing and draw something, anything
1. Save the image to the Pictures directory
1. Wait in Nemo until the saved image is shown with its thumbnail
1. Right-click the saved image in Nemo and select Open With > Pix
1. Switch back to Nemo and go up one directory
1. Switch to Pix and change the image to grayscale, click OK
1. Save the image
1. In Nemo go into the Pictures directory and the image isn't shown and there is an infinite "Loading..." shown in bottom right

(UPDATE: re-tested and confirmed on VirtualBox)

Just to say there are various possible combinations, and it is very easy to get this annoying and scary bug !
And yes, it is very old and widespread.

**Comment by MenthaSuaveolens** [comment] 2021-06-24 15:23
Fortunately the image is not removed from the system. In case you notice the "Loading ..." message shown in the bottom right, then step into another directory and go back - or click on the right cross and reload the directory => saved picture pops up. This is an old bug as I can reproduce it with Nemo 4.6.5

**Closed as completed** 2021-06-24 15:37 UTC
