### ISSUE TITLE
cinnamon: crashes on Run command

### ISSUE THREAD

**Issue by clorophilla** [linuxmint/-mint20.2-beta#27] opened 2021-06-20 21:19 UTC
I use the Run command on Mint (Alt + F2) some times to run something once et al.
After some uses of Run, as soon as I press up on the arrow key to open a previous command, Cinnamon will crash and ask me to restart it. I do that and the problem goes away temporarily.

It's happening to me ever since I started using Mint as my daily driver (from Mint 18 Sara or something).

I hope there's a way to fix this.

**Comment by VaGNaroK** [comment] 2021-06-20 23:14
which command or list of commands did you use?  this makes it easier for others to test and reproduce the problem.

**Comment by clefebvre** [comment] 2021-06-21 12:57
I can't reproduce this.

**Comment by clorophilla** [comment] 2021-06-21 14:55
EDIT: I'm guessing no one read what I wrote after the wall of text below, sorry. Changed the log to a paste.


I have just made it happen again, here are the last lines of /var/sys/syslog:
[https://pastebin.com/raw/yQ3yY8gR](url)


Could this be due to the third party applets I added to the system? I have `temperature@fevimu`, `sysmonitor@orcus` and `betterlock`.

**Comment by clorophilla** [comment] 2021-06-22 07:41
> which command or list of commands did you use? this makes it easier for others to test and reproduce the problem.

I just have some srcpy and rclone commands on its history.
If press the command to Run, I just see an empty box, as expected. Only after I press up on the keyboard then I see the crashes.
But here, I'll give you the history on Run.

>sh -c "rclone --vfs-cache-mode writes mount OneDrive:  ~/OneDrive"
scrcpy --window-borderless --window-x 0 --window-y 0 --window-height 768 -S
sh -c "rclone --vfs-cache-mode writes mount GDrive:  ~/G.Drive"

**Comment by ervasti** [comment] 2021-06-23 04:21
I can reproduce this. The video ends on Cinnamon crash.

https://user-images.githubusercontent.com/67123698/123035086-67fbc900-d3f3-11eb-8078-bbe45a6575d1.mp4

**Comment by clefebvre** [comment] 2021-06-23 09:01
I still can't reproduce this... I put quotes, single quotes, wrong commands in my run box, I go up and down, no crash :(

**Comment by clorophilla** [comment] 2021-06-24 22:49
> I still can't reproduce this... I put quotes, single quotes, wrong commands in my run box, I go up and down, no crash :(

Well, I don't know what else to say on this. It seems to happen the first time I run it after logging in or restarting my computer. The applets I mentioned made no difference.

**Comment by mtwebster** [comment] 2021-06-25 15:26
Which cinnamon themes are being used here? Do you have any adjustments made to your font sizes/scaling?

Does this happen if you create a new user?

**Comment by clorophilla** [comment] 2021-06-27 04:06
> Which cinnamon themes are being used here? Do you have any adjustments made to your font sizes/scaling?
> 
> Does this happen if you create a new user?

I'm using the default theme, didn't touch anything but the wallpaper (using BingWall for this.) Fonts and scaling are the same, nothing touched.

**Comment by clorophilla** [comment] 2021-06-27 04:09
Seems like my problem has quietly gone away, haven't seen the crashes over the past three days. I'm still clueless to why they happened in the first place.

**Comment by clefebvre** [comment] 2021-06-27 11:20
Closing since we couldn't identify the bug.

**Closed as completed by clefebvre** 2021-06-27 11:20 UTC
Labels: not enough info
