### ISSUE TITLE
Bulky - behaves incorrectly for "name + extension"

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/-mint20.2-beta#46] opened 2021-06-22 16:49 UTC
Example:- append 3 digit number to two files, whose names do not contain a dot [i.e. no extension]:-

Case 1:- Select "name only" - the default - gives a correct renaming.
![Screenshot from 2021-06-22 17-00-00](https://user-images.githubusercontent.com/52585119/122961550-68a54880-d37c-11eb-9780-d5b7a29e7b5f.png)
Case 2:- Select "name and extension" - and the numeric parts are duplicated. 
![Screenshot from 2021-06-22 17-01-53](https://user-images.githubusercontent.com/52585119/122961561-693ddf00-d37c-11eb-875c-bdf7e3ef1b1a.png)

Bulky will also perform Case 2 [duplicate numbers], even for files with an extension.

**IMOH I suggest that the idea of a thing called an extension should be removed.
There is a search feature in Bulky, so those who look for dots in Linux filenames can easily find them.**

**Comment by xenopeek** [comment] 2021-06-22 17:44
There was already a small fix for handling extensions https://github.com/linuxmint/bulky/pull/5, which when applied (manually) and retesting your case gives:

![image](https://user-images.githubusercontent.com/21159972/122972946-fa1eb580-d390-11eb-81c8-5c25af4ab2b0.png)

Testing all cases it renames the files "test" and "test.txt" to:

1. **Name only**: test001 and test002.txt
2. **Extension only**: test.001 and test.txt002
3. **Name and extensions**: test001.001 and test002.txt002

If you're renaming a bunch of files of the same type it makes sense to me you might want to either rename only the name, to add some numbering as your example, or to rename only the extension, for example to correct the extension of files, but I'm not sure what the case is for renaming name and extension _independently_ of each other. I'd rather think renaming the full name should be a third option?

**Comment by Jeremy7701** [comment] 2021-06-22 18:09
Quite agree:- just **Name only**, **Extension only** and **Full Name**.

If you really wanted a **Name and extension** you could run Bulky twice - although the circumstances in which you would want this must be very rare.

**Comment by xenopeek** [comment] 2021-06-22 19:06
Even if you and I can't up with a case for why _we_ would want to Insert (or Remove?) on name _and_ extension doesn't mean somebody else won't have a use for it and with the mentioned fix it works as intended.

BTW I also can't come up with a case for why I'd want to Insert (or Remove) on full name. For Change case and Replace I can think of example for why I'd want to rename on name and extension (change old DOS filenames from upper case to lower case or replacing characters in filenames that are forbidden in Windows). In any case if Insert/Remove or in general should offer a different option than name and extension I think that should be a feature request. Not something to tackle during the beta.

Fixed by https://github.com/linuxmint/bulky/commit/3aa17129e6e994511969a1c417272ade805d1ea6

**Closed as completed by xenopeek** 2021-06-22 19:06 UTC
Labels: reproduced
