### ISSUE TITLE
mintupdate: missing translations

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/-mint20.2-beta#5] opened 2021-06-17 23:57 UTC
Hi,

MintUpdate has many missing translations.

Checking for package updates
Checking for Cinnamon spices
Processing updates

On preferences

All of Notifications section on Options tab
Package updates and its description on Automation tab
All of Other Updates section on Automation tab
Performed as root on weekly basis

Best regards

**Comment by clefebvre** [comment] 2021-06-18 08:50
Confirmed.

**Comment by clefebvre** [comment] 2021-06-18 12:01
POT was reuploaded to LP right now. 
Duplicate of https://github.com/linuxmint/mintupdate/issues/685.

**Closed as completed by clefebvre** 2021-06-18 12:01 UTC
