### ISSUE TITLE
bulky: tooltips are not displayed in a stable manner.

### ISSUE THREAD

**Issue by vegam57** [linuxmint/-mint20.2-beta#37] opened 2021-06-21 23:00 UTC
Bulky tooltips may or may not appear and are not displayed in a stable manner. 
![2021-06-22_07-52](https://user-images.githubusercontent.com/78515193/122837708-839d9b80-d32f-11eb-86c2-8ebfc897928f.png)

**Comment by clefebvre** [comment] 2021-06-22 00:46
Please explain or rephrase that first sentence. What do you mean by stable manner?

**Comment by vegam57** [comment] 2021-06-22 00:55
I apologize for my immature English.
I just want to say that hovering or clicking on it doesn't always show up.

**Comment by clefebvre** [comment] 2021-06-22 10:47
I can reproduce it to some extent, the delay seems inconsistent and it's sometimes (rarely) not triggered. This is pure GTK3 though. There's nothing in Bulky which makes this tooltip text different than any other or which grabs focus.

I'll close the issue because I don't think we can do anything about it. If you observe this issue in other applications but only in Cinnamon and not in other DEs, then it could potentially be a Cinnamon issue. Otherwise it's upstream with GTK.

**Closed as completed by clefebvre** 2021-06-22 10:47 UTC
Labels: not enough info
